// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export type GeneratedDirtModelOption = {
  id: string;
  modelId: string;
  name: string;
  url: string;
  slot: 1 | 2 | 3 | 4 | null;
  scope: "global" | "house";
  houseId?: string;
};

export const dirtModelOptionsGenerated = [
  {
    "id": "dirt_1",
    "modelId": "dirt_1",
    "name": "Грязь 1",
    "url": "/models/dirt/slots/dirt_1.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_2",
    "modelId": "dirt_2",
    "name": "Грязь 2",
    "url": "/models/dirt/slots/dirt_2.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_3",
    "modelId": "dirt_3",
    "name": "Грязь 3",
    "url": "/models/dirt/slots/dirt_3.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_4",
    "modelId": "dirt_4",
    "name": "Грязь 4",
    "url": "/models/dirt/slots/dirt_4.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_5",
    "modelId": "dirt_5",
    "name": "Грязь 5",
    "url": "/models/dirt/slots/dirt_5.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_6",
    "modelId": "dirt_6",
    "name": "Грязь 6",
    "url": "/models/dirt/slots/dirt_6.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_7",
    "modelId": "dirt_7",
    "name": "Грязь 7",
    "url": "/models/dirt/slots/dirt_7.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_8",
    "modelId": "dirt_8",
    "name": "Грязь 8",
    "url": "/models/dirt/slots/dirt_8.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_9",
    "modelId": "dirt_9",
    "name": "Грязь 9",
    "url": "/models/dirt/slots/dirt_9.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_10",
    "modelId": "dirt_10",
    "name": "Грязь 10",
    "url": "/models/dirt/slots/dirt_10.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_11",
    "modelId": "dirt_11",
    "name": "Грязь 11",
    "url": "/models/dirt/slots/dirt_11.glb",
    "slot": null,
    "scope": "global"
  },
  {
    "id": "dirt_12",
    "modelId": "dirt_12",
    "name": "Грязь 12",
    "url": "/models/dirt/slots/dirt_12.glb",
    "slot": null,
    "scope": "global"
  }
] as const;
