// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const giftModelsGenerated = {
  "bird_1": {
    "bird": "/models/gifts/bird/bird_1.glb"
  },
  "bird_2": {
    "bird": "/models/gifts/bird/bird_2.glb"
  },
  "candle_1": {
    "candle": "/models/gifts/candle/candle_1.glb"
  },
  "candle_10": {
    "candle": "/models/gifts/candle/candle_10.glb"
  },
  "candle_11": {
    "candle": "/models/gifts/candle/candle_11.glb"
  },
  "candle_12": {
    "candle": "/models/gifts/candle/candle_12.glb"
  },
  "candle_2": {
    "candle": "/models/gifts/candle/candle_2.glb"
  },
  "candle_3": {
    "candle": "/models/gifts/candle/candle_3.glb"
  },
  "candle_4": {
    "candle": "/models/gifts/candle/candle_4.glb"
  },
  "candle_5": {
    "candle": "/models/gifts/candle/candle_5.glb"
  },
  "candle_6": {
    "candle": "/models/gifts/candle/candle_6.glb"
  },
  "candle_7": {
    "candle": "/models/gifts/candle/candle_7.glb"
  },
  "candle_8": {
    "candle": "/models/gifts/candle/candle_8.glb"
  },
  "candle_9": {
    "candle": "/models/gifts/candle/candle_9.glb"
  },
  "flower_1": {
    "flower": "/models/gifts/flower/flower_1.glb"
  },
  "flower_10": {
    "flower": "/models/gifts/flower/flower_10.glb"
  },
  "flower_11": {
    "flower": "/models/gifts/flower/flower_11.glb"
  },
  "flower_12": {
    "flower": "/models/gifts/flower/flower_12.glb"
  },
  "flower_2": {
    "flower": "/models/gifts/flower/flower_2.glb"
  },
  "flower_3": {
    "flower": "/models/gifts/flower/flower_3.glb"
  },
  "flower_4": {
    "flower": "/models/gifts/flower/flower_4.glb"
  },
  "flower_5": {
    "flower": "/models/gifts/flower/flower_5.glb"
  },
  "flower_6": {
    "flower": "/models/gifts/flower/flower_6.glb"
  },
  "flower_7": {
    "flower": "/models/gifts/flower/flower_7.glb"
  },
  "flower_8": {
    "flower": "/models/gifts/flower/flower_8.glb"
  },
  "flower_9": {
    "flower": "/models/gifts/flower/flower_9.glb"
  },
  "meal_1": {
    "meal": "/models/gifts/meal/meal_1.glb"
  },
  "meal_10": {
    "meal": "/models/gifts/meal/meal_10.glb"
  },
  "meal_11": {
    "meal": "/models/gifts/meal/meal_11.glb"
  },
  "meal_12": {
    "meal": "/models/gifts/meal/meal_12.glb"
  },
  "meal_13": {
    "meal": "/models/gifts/meal/meal_13.glb"
  },
  "meal_14": {
    "meal": "/models/gifts/meal/meal_14.glb"
  },
  "meal_15": {
    "meal": "/models/gifts/meal/meal_15.glb"
  },
  "meal_2": {
    "meal": "/models/gifts/meal/meal_2.glb"
  },
  "meal_3": {
    "meal": "/models/gifts/meal/meal_3.glb"
  },
  "meal_4": {
    "meal": "/models/gifts/meal/meal_4.glb"
  },
  "meal_5": {
    "meal": "/models/gifts/meal/meal_5.glb"
  },
  "meal_6": {
    "meal": "/models/gifts/meal/meal_6.glb"
  },
  "meal_7": {
    "meal": "/models/gifts/meal/meal_7.glb"
  },
  "meal_8": {
    "meal": "/models/gifts/meal/meal_8.glb"
  },
  "meal_9": {
    "meal": "/models/gifts/meal/meal_9.glb"
  },
  "star_1": {
    "star": "/models/gifts/star/star_1.glb"
  },
  "star_2": {
    "star": "/models/gifts/star/star_2.glb"
  },
  "star_3": {
    "star": "/models/gifts/star/star_3.glb"
  },
  "star_4": {
    "star": "/models/gifts/star/star_4.glb"
  },
  "star_5": {
    "star": "/models/gifts/star/star_5.glb"
  },
  "star_6": {
    "star": "/models/gifts/star/star_6.glb"
  },
  "star_7": {
    "star": "/models/gifts/star/star_7.glb"
  },
  "star_8": {
    "star": "/models/gifts/star/star_8.glb"
  },
  "toy_1": {
    "toy": "/models/gifts/toy/toy_1.glb"
  },
  "toy_10": {
    "toy": "/models/gifts/toy/toy_10.glb"
  },
  "toy_11": {
    "toy": "/models/gifts/toy/toy_11.glb"
  },
  "toy_12": {
    "toy": "/models/gifts/toy/toy_12.glb"
  },
  "toy_13": {
    "toy": "/models/gifts/toy/toy_13.glb"
  },
  "toy_14": {
    "toy": "/models/gifts/toy/toy_14.glb"
  },
  "toy_15": {
    "toy": "/models/gifts/toy/toy_15.glb"
  },
  "toy_16": {
    "toy": "/models/gifts/toy/toy_16.glb"
  },
  "toy_17": {
    "toy": "/models/gifts/toy/toy_17.glb"
  },
  "toy_18": {
    "toy": "/models/gifts/toy/toy_18.glb"
  },
  "toy_19": {
    "toy": "/models/gifts/toy/toy_19.glb"
  },
  "toy_2": {
    "toy": "/models/gifts/toy/toy_2.glb"
  },
  "toy_20": {
    "toy": "/models/gifts/toy/toy_20.glb"
  },
  "toy_21": {
    "toy": "/models/gifts/toy/toy_21.glb"
  },
  "toy_22": {
    "toy": "/models/gifts/toy/toy_22.glb"
  },
  "toy_23": {
    "toy": "/models/gifts/toy/toy_23.glb"
  },
  "toy_24": {
    "toy": "/models/gifts/toy/toy_24.glb"
  },
  "toy_3": {
    "toy": "/models/gifts/toy/toy_3.glb"
  },
  "toy_4": {
    "toy": "/models/gifts/toy/toy_4.glb"
  },
  "toy_5": {
    "toy": "/models/gifts/toy/toy_5.glb"
  },
  "toy_6": {
    "toy": "/models/gifts/toy/toy_6.glb"
  },
  "toy_7": {
    "toy": "/models/gifts/toy/toy_7.glb"
  },
  "toy_8": {
    "toy": "/models/gifts/toy/toy_8.glb"
  },
  "toy_9": {
    "toy": "/models/gifts/toy/toy_9.glb"
  }
} as const;
