// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const giftModelsGenerated = {
  "candle_1": {
    "candle": "/models/gifts/candle/candle_1.glb"
  },
  "candle_10": {
    "candle": "/models/gifts/candle/candle_10.glb"
  },
  "candle_11": {
    "candle": "/models/gifts/candle/candle_11.glb"
  },
  "candle_12": {
    "candle": "/models/gifts/candle/candle_12.glb"
  },
  "candle_2": {
    "candle": "/models/gifts/candle/candle_2.glb"
  },
  "candle_3": {
    "candle": "/models/gifts/candle/candle_3.glb"
  },
  "candle_4": {
    "candle": "/models/gifts/candle/candle_4.glb"
  },
  "candle_5": {
    "candle": "/models/gifts/candle/candle_5.glb"
  },
  "candle_6": {
    "candle": "/models/gifts/candle/candle_6.glb"
  },
  "candle_7": {
    "candle": "/models/gifts/candle/candle_7.glb"
  },
  "candle_8": {
    "candle": "/models/gifts/candle/candle_8.glb"
  },
  "candle_9": {
    "candle": "/models/gifts/candle/candle_9.glb"
  },
  "flower_1": {
    "flower": "/models/gifts/flower/flower_1.glb"
  },
  "flower_10": {
    "flower": "/models/gifts/flower/flower_10.glb"
  },
  "flower_11": {
    "flower": "/models/gifts/flower/flower_11.glb"
  },
  "flower_12": {
    "flower": "/models/gifts/flower/flower_12.glb"
  },
  "flower_2": {
    "flower": "/models/gifts/flower/flower_2.glb"
  },
  "flower_3": {
    "flower": "/models/gifts/flower/flower_3.glb"
  },
  "flower_4": {
    "flower": "/models/gifts/flower/flower_4.glb"
  },
  "flower_5": {
    "flower": "/models/gifts/flower/flower_5.glb"
  },
  "flower_6": {
    "flower": "/models/gifts/flower/flower_6.glb"
  },
  "flower_7": {
    "flower": "/models/gifts/flower/flower_7.glb"
  },
  "flower_8": {
    "flower": "/models/gifts/flower/flower_8.glb"
  },
  "flower_9": {
    "flower": "/models/gifts/flower/flower_9.glb"
  },
  "star_1": {
    "star": "/models/gifts/star/star_1.glb"
  },
  "star_2": {
    "star": "/models/gifts/star/star_2.glb"
  },
  "star_3": {
    "star": "/models/gifts/star/star_3.glb"
  },
  "star_4": {
    "star": "/models/gifts/star/star_4.glb"
  },
  "star_5": {
    "star": "/models/gifts/star/star_5.glb"
  },
  "star_6": {
    "star": "/models/gifts/star/star_6.glb"
  },
  "star_7": {
    "star": "/models/gifts/star/star_7.glb"
  },
  "star_8": {
    "star": "/models/gifts/star/star_8.glb"
  }
} as const;
