// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const giftModelsGenerated = {
  "candle": {
    "default": "/models/gifts/candle.glb"
  },
  "flower_1": {
    "flowers": "/models/gifts/flowers/flower_1.glb"
  },
  "flower_10": {
    "flowers": "/models/gifts/flowers/flower_10.glb"
  },
  "flower_11": {
    "flowers": "/models/gifts/flowers/flower_11.glb"
  },
  "flower_12": {
    "flowers": "/models/gifts/flowers/flower_12.glb"
  },
  "flower_2": {
    "flowers": "/models/gifts/flowers/flower_2.glb"
  },
  "flower_3": {
    "flowers": "/models/gifts/flowers/flower_3.glb"
  },
  "flower_4": {
    "flowers": "/models/gifts/flowers/flower_4.glb"
  },
  "flower_5": {
    "flowers": "/models/gifts/flowers/flower_5.glb"
  },
  "flower_6": {
    "flowers": "/models/gifts/flowers/flower_6.glb"
  },
  "flower_7": {
    "flowers": "/models/gifts/flowers/flower_7.glb"
  },
  "flower_8": {
    "flowers": "/models/gifts/flowers/flower_8.glb"
  },
  "flower_9": {
    "flowers": "/models/gifts/flowers/flower_9.glb"
  }
} as const;
