// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const environmentModelByIdGenerated = {
  "3": "/models/terrains/TERRAIN_3_summer.glb"
} as const;
export const environmentSeasonModelsByIdGenerated = {
  "3": {
    "autumn": "/models/terrains/TERRAIN_3_autumn.glb",
    "spring": "/models/terrains/TERRAIN_3_spring.glb",
    "summer": "/models/terrains/TERRAIN_3_summer.glb",
    "winter": "/models/terrains/TERRAIN_3_winter.glb"
  }
} as const;
export const houseModelByIdGenerated = {
  "andreyvbvbvb_1": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_1.glb",
  "andreyvbvbvb_2": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_2.glb",
  "andreyvbvbvb_3": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_3.glb",
  "andreyvbvbvb_4": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_4.glb",
  "andreyvbvbvb_5": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_5.glb",
  "andreyvbvbvb_6": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_6.glb",
  "andreyvbvbvb_7": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_7.glb",
  "andreyvbvbvb_8": "/models/houses/extra/andreyvbvbvb/DOM_andreyvbvbvb_8.glb",
  "budka_1__base": "/models/houses/DOM_budka_1__base.glb",
  "budka_2__base": "/models/houses/DOM_budka_2__base.glb",
  "budka_2__second": "/models/houses/DOM_budka_2__second.glb",
  "budka_3__base": "/models/houses/DOM_budka_3__base.glb",
  "budka_4__base": "/models/houses/DOM_budka_4__base.glb",
  "budka_5__base": "/models/houses/DOM_budka_5__base.glb",
  "budka_5__second": "/models/houses/DOM_budka_5__second.glb",
  "budka_6__base": "/models/houses/DOM_budka_6__base.glb",
  "budka_7__base": "/models/houses/DOM_budka_7__base.glb",
  "budka_7__brown": "/models/houses/DOM_budka_7__brown.glb",
  "budka_7__soso": "/models/houses/DOM_budka_7__soso.glb",
  "budka_7__tuntun": "/models/houses/DOM_budka_7__tuntun.glb",
  "budka_7__white": "/models/houses/DOM_budka_7__white.glb",
  "budka_8__base": "/models/houses/DOM_budka_8__base.glb",
  "budka_8__brown": "/models/houses/DOM_budka_8__brown.glb",
  "budka_8__stone": "/models/houses/DOM_budka_8__stone.glb",
  "budka_8__toy": "/models/houses/DOM_budka_8__toy.glb",
  "budka_8__white": "/models/houses/DOM_budka_8__white.glb",
  "kotik_1__base": "/models/houses/DOM_kotik_1__base.glb",
  "kotik_1__second": "/models/houses/DOM_kotik_1__second.glb",
  "kotik_2__base": "/models/houses/DOM_kotik_2__base.glb",
  "kotik_2__second": "/models/houses/DOM_kotik_2__second.glb",
  "kotik_3__base": "/models/houses/DOM_kotik_3__base.glb",
  "kotik_4__base": "/models/houses/DOM_kotik_4__base.glb",
  "kotik_4__second": "/models/houses/DOM_kotik_4__second.glb",
  "kotik_4__third": "/models/houses/DOM_kotik_4__third.glb",
  "kotik_5__base": "/models/houses/DOM_kotik_5__base.glb",
  "kotik_5__second": "/models/houses/DOM_kotik_5__second.glb",
  "kotik_6__base": "/models/houses/DOM_kotik_6__base.glb",
  "mat_1__base": "/models/houses/DOM_mat_1__base.glb",
  "mat_1__fourth": "/models/houses/DOM_mat_1__fourth.glb",
  "mat_1__second": "/models/houses/DOM_mat_1__second.glb",
  "mat_1__third": "/models/houses/DOM_mat_1__third.glb"
} as const;
export const roofModelByIdGenerated = {
  "roof_1": "/models/parts/roof/roof_1.glb",
  "roof_2": "/models/parts/roof/roof_2.glb"
} as const;
export const wallModelByIdGenerated = {
  "wall_1": "/models/parts/wall/wall_1.glb",
  "wall_2": "/models/parts/wall/wall_2.glb"
} as const;
export const signModelByIdGenerated = {
  "sign_1": "/models/parts/sign/sign_1.glb",
  "sign_2": "/models/parts/sign/sign_2.glb",
  "sign_3": "/models/parts/sign/sign_3.glb",
  "sign_4": "/models/parts/sign/sign_4.glb",
  "sign_5": "/models/parts/sign/sign_5.glb",
  "sign_6": "/models/parts/sign/sign_6.glb",
  "sign_7": "/models/parts/sign/sign_7.glb",
  "sign_8": "/models/parts/sign/sign_8.glb",
  "sign_9": "/models/parts/sign/sign_9.glb",
  "sign_10": "/models/parts/sign/sign_10.glb",
  "sign_11": "/models/parts/sign/sign_11.glb",
  "sign_12": "/models/parts/sign/sign_12.glb"
} as const;
export const frameLeftModelByIdGenerated = {
  "frame_left_1": "/models/parts/frame_left/frame_left_1.glb",
  "frame_left_2": "/models/parts/frame_left/frame_left_2.glb"
} as const;
export const frameRightModelByIdGenerated = {
  "frame_right_1": "/models/parts/frame_right/frame_right_1.glb",
  "frame_right_2": "/models/parts/frame_right/frame_right_2.glb"
} as const;
export const matModelByIdGenerated = {
  "mat_1": "/models/parts/mat/mat_1.glb",
  "mat_2": "/models/parts/mat/mat_2.glb",
  "mat_3": "/models/parts/mat/mat_3.glb",
  "mat_4": "/models/parts/mat/mat_4.glb",
  "mat_5": "/models/parts/mat/mat_5.glb",
  "mat_6": "/models/parts/mat/mat_6.glb",
  "mat_7": "/models/parts/mat/mat_7.glb",
  "mat_8": "/models/parts/mat/mat_8.glb",
  "mat_9": "/models/parts/mat/mat_9.glb",
  "mat_10": "/models/parts/mat/mat_10.glb",
  "mat_11": "/models/parts/mat/mat_11.glb",
  "mat_12": "/models/parts/mat/mat_12.glb",
  "mat_13": "/models/parts/mat/mat_13.glb",
  "mat_14": "/models/parts/mat/mat_14.glb",
  "mat_15": "/models/parts/mat/mat_15.glb"
} as const;
export const bowlFoodModelByIdGenerated = {
  "bowl_food_1": "/models/parts/bowl_food/bowl_food_1.glb",
  "bowl_food_2": "/models/parts/bowl_food/bowl_food_2.glb",
  "bowl_food_3": "/models/parts/bowl_food/bowl_food_3.glb",
  "bowl_food_4": "/models/parts/bowl_food/bowl_food_4.glb",
  "bowl_food_5": "/models/parts/bowl_food/bowl_food_5.glb",
  "bowl_food_6": "/models/parts/bowl_food/bowl_food_6.glb",
  "bowl_food_7": "/models/parts/bowl_food/bowl_food_7.glb",
  "bowl_food_8": "/models/parts/bowl_food/bowl_food_8.glb"
} as const;
export const bowlWaterModelByIdGenerated = {
  "bowl_water_1": "/models/parts/bowl_water/bowl_water_1.glb",
  "bowl_water_2": "/models/parts/bowl_water/bowl_water_2.glb",
  "bowl_water_3": "/models/parts/bowl_water/bowl_water_3.glb",
  "bowl_water_4": "/models/parts/bowl_water/bowl_water_4.glb",
  "bowl_water_5": "/models/parts/bowl_water/bowl_water_5.glb",
  "bowl_water_6": "/models/parts/bowl_water/bowl_water_6.glb",
  "bowl_water_7": "/models/parts/bowl_water/bowl_water_7.glb",
  "bowl_water_8": "/models/parts/bowl_water/bowl_water_8.glb",
  "bowl_water_9": "/models/parts/bowl_water/extra/andreyvbvbvb/bowl_water_9.glb"
} as const;
export const partModelGroupsGenerated = {
  "roof": {
    "roof_1": "/models/parts/roof/roof_1.glb",
    "roof_2": "/models/parts/roof/roof_2.glb"
  },
  "wall": {
    "wall_1": "/models/parts/wall/wall_1.glb",
    "wall_2": "/models/parts/wall/wall_2.glb"
  },
  "sign": {
    "sign_1": "/models/parts/sign/sign_1.glb",
    "sign_2": "/models/parts/sign/sign_2.glb",
    "sign_3": "/models/parts/sign/sign_3.glb",
    "sign_4": "/models/parts/sign/sign_4.glb",
    "sign_5": "/models/parts/sign/sign_5.glb",
    "sign_6": "/models/parts/sign/sign_6.glb",
    "sign_7": "/models/parts/sign/sign_7.glb",
    "sign_8": "/models/parts/sign/sign_8.glb",
    "sign_9": "/models/parts/sign/sign_9.glb",
    "sign_10": "/models/parts/sign/sign_10.glb",
    "sign_11": "/models/parts/sign/sign_11.glb",
    "sign_12": "/models/parts/sign/sign_12.glb"
  },
  "frame_left": {
    "frame_left_1": "/models/parts/frame_left/frame_left_1.glb",
    "frame_left_2": "/models/parts/frame_left/frame_left_2.glb"
  },
  "frame_right": {
    "frame_right_1": "/models/parts/frame_right/frame_right_1.glb",
    "frame_right_2": "/models/parts/frame_right/frame_right_2.glb"
  },
  "mat": {
    "mat_1": "/models/parts/mat/mat_1.glb",
    "mat_2": "/models/parts/mat/mat_2.glb",
    "mat_3": "/models/parts/mat/mat_3.glb",
    "mat_4": "/models/parts/mat/mat_4.glb",
    "mat_5": "/models/parts/mat/mat_5.glb",
    "mat_6": "/models/parts/mat/mat_6.glb",
    "mat_7": "/models/parts/mat/mat_7.glb",
    "mat_8": "/models/parts/mat/mat_8.glb",
    "mat_9": "/models/parts/mat/mat_9.glb",
    "mat_10": "/models/parts/mat/mat_10.glb",
    "mat_11": "/models/parts/mat/mat_11.glb",
    "mat_12": "/models/parts/mat/mat_12.glb",
    "mat_13": "/models/parts/mat/mat_13.glb",
    "mat_14": "/models/parts/mat/mat_14.glb",
    "mat_15": "/models/parts/mat/mat_15.glb"
  },
  "bowl_food": {
    "bowl_food_1": "/models/parts/bowl_food/bowl_food_1.glb",
    "bowl_food_2": "/models/parts/bowl_food/bowl_food_2.glb",
    "bowl_food_3": "/models/parts/bowl_food/bowl_food_3.glb",
    "bowl_food_4": "/models/parts/bowl_food/bowl_food_4.glb",
    "bowl_food_5": "/models/parts/bowl_food/bowl_food_5.glb",
    "bowl_food_6": "/models/parts/bowl_food/bowl_food_6.glb",
    "bowl_food_7": "/models/parts/bowl_food/bowl_food_7.glb",
    "bowl_food_8": "/models/parts/bowl_food/bowl_food_8.glb"
  },
  "bowl_water": {
    "bowl_water_1": "/models/parts/bowl_water/bowl_water_1.glb",
    "bowl_water_2": "/models/parts/bowl_water/bowl_water_2.glb",
    "bowl_water_3": "/models/parts/bowl_water/bowl_water_3.glb",
    "bowl_water_4": "/models/parts/bowl_water/bowl_water_4.glb",
    "bowl_water_5": "/models/parts/bowl_water/bowl_water_5.glb",
    "bowl_water_6": "/models/parts/bowl_water/bowl_water_6.glb",
    "bowl_water_7": "/models/parts/bowl_water/bowl_water_7.glb",
    "bowl_water_8": "/models/parts/bowl_water/bowl_water_8.glb",
    "bowl_water_9": "/models/parts/bowl_water/extra/andreyvbvbvb/bowl_water_9.glb"
  },
  "candle": {
    "candle_1": "/models/parts/candle/candle_1.glb",
    "candle_2": "/models/parts/candle/candle_2.glb",
    "candle_3": "/models/parts/candle/candle_3.glb",
    "candle_4": "/models/parts/candle/candle_4.glb",
    "candle_5": "/models/parts/candle/candle_5.glb",
    "candle_6": "/models/parts/candle/candle_6.glb",
    "candle_7": "/models/parts/candle/candle_7.glb",
    "candle_8": "/models/parts/candle/candle_8.glb",
    "candle_9": "/models/parts/candle/candle_9.glb",
    "candle_10": "/models/parts/candle/candle_10.glb",
    "candle_11": "/models/parts/candle/candle_11.glb",
    "candle_12": "/models/parts/candle/candle_12.glb"
  },
  "flower": {
    "flower_1": "/models/parts/flower/flower_1.glb",
    "flower_2": "/models/parts/flower/flower_2.glb",
    "flower_3": "/models/parts/flower/flower_3.glb",
    "flower_4": "/models/parts/flower/flower_4.glb",
    "flower_5": "/models/parts/flower/flower_5.glb",
    "flower_6": "/models/parts/flower/flower_6.glb",
    "flower_7": "/models/parts/flower/flower_7.glb",
    "flower_8": "/models/parts/flower/flower_8.glb",
    "flower_9": "/models/parts/flower/flower_9.glb",
    "flower_10": "/models/parts/flower/flower_10.glb",
    "flower_11": "/models/parts/flower/flower_11.glb",
    "flower_12": "/models/parts/flower/flower_12.glb"
  },
  "ktochka": {
    "ktochka_1": "/models/parts/ktochka/ktochka_1.glb",
    "ktochka_2": "/models/parts/ktochka/ktochka_2.glb",
    "ktochka_3": "/models/parts/ktochka/ktochka_3.glb",
    "ktochka_4": "/models/parts/ktochka/ktochka_4.glb",
    "ktochka_5": "/models/parts/ktochka/ktochka_5.glb",
    "ktochka_6": "/models/parts/ktochka/ktochka_6.glb",
    "ktochka_7": "/models/parts/ktochka/ktochka_7.glb",
    "ktochka_8": "/models/parts/ktochka/ktochka_8.glb"
  }
} as const;
