// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export type GeneratedOptionItem = {
  id: string;
  name: string;
  description: string;
};

export const environmentOptionsGenerated = [
  {
    "id": "summer",
    "name": "Лето",
    "description": "Автодобавлено"
  },
  {
    "id": "summer_1",
    "name": "Лето 1",
    "description": "Автодобавлено"
  },
  {
    "id": "spring",
    "name": "Весна",
    "description": "Автодобавлено"
  },
  {
    "id": "autumn",
    "name": "Осень",
    "description": "Автодобавлено"
  },
  {
    "id": "winter",
    "name": "Зима",
    "description": "Автодобавлено"
  },
  {
    "id": "winter_1",
    "name": "Зима 1",
    "description": "Автодобавлено"
  }
] as const;
export const houseOptionsGenerated = [
  {
    "id": "budka_1",
    "name": "Будка 1",
    "description": "Вариант 1"
  },
  {
    "id": "budka_2",
    "name": "Будка 2",
    "description": "Вариант 2"
  }
] as const;
export const roofOptionsGenerated = [
  {
    "id": "roof_1",
    "name": "Крыша 1",
    "description": "Вариант 1"
  },
  {
    "id": "roof_2",
    "name": "Крыша 2",
    "description": "Вариант 2"
  }
] as const;
export const wallOptionsGenerated = [
  {
    "id": "wall_1",
    "name": "Стены 1",
    "description": "Вариант 1"
  },
  {
    "id": "wall_2",
    "name": "Стены 2",
    "description": "Вариант 2"
  }
] as const;
export const signOptionsGenerated = [
  {
    "id": "sign_1",
    "name": "Украшение 1",
    "description": "Вариант 1"
  },
  {
    "id": "sign_2",
    "name": "Украшение 2",
    "description": "Вариант 2"
  }
] as const;
export const frameLeftOptionsGenerated = [
  {
    "id": "frame_left_1",
    "name": "Рамка слева 1",
    "description": "Вариант 1"
  },
  {
    "id": "frame_left_2",
    "name": "Рамка слева 2",
    "description": "Вариант 2"
  }
] as const;
export const frameRightOptionsGenerated = [
  {
    "id": "frame_right_1",
    "name": "Рамка справа 1",
    "description": "Вариант 1"
  },
  {
    "id": "frame_right_2",
    "name": "Рамка справа 2",
    "description": "Вариант 2"
  }
] as const;
export const matOptionsGenerated = [
  {
    "id": "mat_1",
    "name": "Коврик 1",
    "description": "Вариант 1"
  },
  {
    "id": "mat_2",
    "name": "Коврик 2",
    "description": "Вариант 2"
  }
] as const;
export const bowlFoodOptionsGenerated = [
  {
    "id": "bowl_food_1",
    "name": "Миска еды 1",
    "description": "Вариант 1"
  },
  {
    "id": "bowl_food_2",
    "name": "Миска еды 2",
    "description": "Вариант 2"
  },
  {
    "id": "bowl_food_3",
    "name": "Миска еды 3",
    "description": "Вариант 3"
  },
  {
    "id": "bowl_food_4",
    "name": "Миска еды 4",
    "description": "Вариант 4"
  },
  {
    "id": "bowl_food_5",
    "name": "Миска еды 5",
    "description": "Вариант 5"
  },
  {
    "id": "bowl_food_6",
    "name": "Миска еды 6",
    "description": "Вариант 6"
  },
  {
    "id": "bowl_food_7",
    "name": "Миска еды 7",
    "description": "Вариант 7"
  }
] as const;
export const bowlWaterOptionsGenerated = [
  {
    "id": "bowl_water_1",
    "name": "Миска воды 1",
    "description": "Вариант 1"
  },
  {
    "id": "bowl_water_2",
    "name": "Миска воды 2",
    "description": "Вариант 2"
  }
] as const;
