// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const environmentModelByIdGenerated = {
  "2": "/models/terrains/TERRAIN_2_summer.glb"
} as const;
export const environmentSeasonModelsByIdGenerated = {
  "2": {
    "autumn": "/models/terrains/TERRAIN_2_autumn.glb",
    "spring": "/models/terrains/TERRAIN_2_spring.glb",
    "summer": "/models/terrains/TERRAIN_2_summer.glb",
    "winter": "/models/terrains/TERRAIN_2_winter.glb"
  }
} as const;
export const houseModelByIdGenerated = {
  "budka_1__base": "/models/houses/DOM_budka_1__base.glb",
  "budka_1__brown": "/models/houses/DOM_budka_1__brown.glb",
  "budka_1__soso": "/models/houses/DOM_budka_1__soso.glb",
  "budka_1__tuntun": "/models/houses/DOM_budka_1__tuntun.glb",
  "budka_1__white": "/models/houses/DOM_budka_1__white.glb",
  "budka_2__base": "/models/houses/DOM_budka_2__base.glb",
  "budka_2__brown": "/models/houses/DOM_budka_2__brown.glb",
  "budka_2__normal": "/models/houses/DOM_budka_2__normal.glb",
  "budka_2__toy": "/models/houses/DOM_budka_2__toy.glb",
  "budka_2__white": "/models/houses/DOM_budka_2__white.glb"
} as const;
export const roofModelByIdGenerated = {
  "roof_1": "/models/parts/roof/roof_1.glb",
  "roof_2": "/models/parts/roof/roof_2.glb"
} as const;
export const wallModelByIdGenerated = {
  "wall_1": "/models/parts/wall/wall_1.glb",
  "wall_2": "/models/parts/wall/wall_2.glb"
} as const;
export const signModelByIdGenerated = {
  "sign_1": "/models/parts/sign/sign_1.glb",
  "sign_2": "/models/parts/sign/sign_2.glb"
} as const;
export const frameLeftModelByIdGenerated = {
  "frame_left_1": "/models/parts/frame_left/frame_left_1.glb",
  "frame_left_2": "/models/parts/frame_left/frame_left_2.glb"
} as const;
export const frameRightModelByIdGenerated = {
  "frame_right_1": "/models/parts/frame_right/frame_right_1.glb",
  "frame_right_2": "/models/parts/frame_right/frame_right_2.glb"
} as const;
export const matModelByIdGenerated = {
  "mat_1": "/models/parts/mat/mat_1.glb",
  "mat_2": "/models/parts/mat/mat_2.glb",
  "mat_3": "/models/parts/mat/mat_3.glb",
  "mat_4": "/models/parts/mat/mat_4.glb",
  "mat_5": "/models/parts/mat/mat_5.glb",
  "mat_6": "/models/parts/mat/mat_6.glb",
  "mat_7": "/models/parts/mat/mat_7.glb",
  "mat_8": "/models/parts/mat/mat_8.glb",
  "mat_9": "/models/parts/mat/mat_9.glb",
  "mat_10": "/models/parts/mat/mat_10.glb",
  "mat_11": "/models/parts/mat/mat_11.glb",
  "mat_12": "/models/parts/mat/mat_12.glb",
  "mat_13": "/models/parts/mat/mat_13.glb",
  "mat_14": "/models/parts/mat/mat_14.glb",
  "mat_15": "/models/parts/mat/mat_15.glb"
} as const;
export const bowlFoodModelByIdGenerated = {
  "bowl_food_1": "/models/parts/bowl_food/bowl_food_1.glb",
  "bowl_food_2": "/models/parts/bowl_food/bowl_food_2.glb",
  "bowl_food_3": "/models/parts/bowl_food/bowl_food_3.glb",
  "bowl_food_4": "/models/parts/bowl_food/bowl_food_4.glb",
  "bowl_food_5": "/models/parts/bowl_food/bowl_food_5.glb",
  "bowl_food_6": "/models/parts/bowl_food/bowl_food_6.glb",
  "bowl_food_7": "/models/parts/bowl_food/bowl_food_7.glb"
} as const;
export const bowlWaterModelByIdGenerated = {
  "bowl_water_1": "/models/parts/bowl_water/bowl_water_1.glb",
  "bowl_water_2": "/models/parts/bowl_water/bowl_water_2.glb",
  "bowl_water_3": "/models/parts/bowl_water/bowl_water_3.glb",
  "bowl_water_4": "/models/parts/bowl_water/bowl_water_4.glb",
  "bowl_water_5": "/models/parts/bowl_water/bowl_water_5.glb",
  "bowl_water_6": "/models/parts/bowl_water/bowl_water_6.glb",
  "bowl_water_7": "/models/parts/bowl_water/bowl_water_7.glb",
  "bowl_water_8": "/models/parts/bowl_water/bowl_water_8.glb"
} as const;
