// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const houseSlotsGenerated = {
  "andreyvbvbvb_1": {
    "flower_slot_1": "flower_slot_1",
    "flower_slot_2": "flower_slot_2",
    "flower_slot_3": "flower_slot_3",
    "flower_slot_4": "flower_slot_4",
    "flower_slot_5": "flower_slot_5",
    "flower_slot_6": "flower_slot_6",
    "flower_slot_7": "flower_slot_7",
    "flower_slot_8": "flower_slot_8",
    "flower_slot_9": "flower_slot_9",
    "flower_slot_10": "flower_slot_10"
  },
  "budka_1__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_2__base": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_2__second": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_3__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_4__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_5__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_5__second": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_6__base": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_7__base": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_7__brown": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_7__soso": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_7__tuntun": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_7__white": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_8__base": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_8__brown": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_8__stone": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_8__toy": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "budka_8__white": {
    "sign": "sign_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_1__base": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_1__second": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_2__base": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_2__second": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_3__base": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_4__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_4__second": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_4__third": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_5__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_5__second": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "kotik_6__base": {
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "mat_1__base": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "mat_1__fourth": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "mat_1__second": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  },
  "mat_1__third": {
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  }
} as const;
