// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const environmentModelByIdGenerated = {
  "summer": "/models/terrains/TERRAIN_summer.glb",
  "summer_1": "/models/terrains/TERRAIN_summer_1.glb",
  "spring": "/models/terrains/TERRAIN_spring.glb",
  "autumn": "/models/terrains/TERRAIN_autumn.glb",
  "winter": "/models/terrains/TERRAIN_winter.glb",
  "winter_1": "/models/terrains/TERRAIN_winter_1.glb"
} as const;
export const houseModelByIdGenerated = {
  "budka_1": "/models/houses/DOM_budka_1.glb",
  "budka_2": "/models/houses/DOM_budka_2.glb"
} as const;
export const roofModelByIdGenerated = {
  "roof_1": "/models/parts/roof/roof_1.glb",
  "roof_2": "/models/parts/roof/roof_2.glb"
} as const;
export const wallModelByIdGenerated = {
  "wall_1": "/models/parts/wall/wall_1.glb",
  "wall_2": "/models/parts/wall/wall_2.glb"
} as const;
export const signModelByIdGenerated = {
  "sign_1": "/models/parts/sign/sign_1.glb",
  "sign_2": "/models/parts/sign/sign_2.glb"
} as const;
export const frameLeftModelByIdGenerated = {
  "frame_left_1": "/models/parts/frame_left/frame_left_1.glb",
  "frame_left_2": "/models/parts/frame_left/frame_left_2.glb"
} as const;
export const frameRightModelByIdGenerated = {
  "frame_right_1": "/models/parts/frame_right/frame_right_1.glb",
  "frame_right_2": "/models/parts/frame_right/frame_right_2.glb"
} as const;
export const matModelByIdGenerated = {
  "mat_1": "/models/parts/mat/mat_1.glb",
  "mat_2": "/models/parts/mat/mat_2.glb"
} as const;
export const bowlFoodModelByIdGenerated = {
  "bowl_food_1": "/models/parts/bowl_food/bowl_food_1.glb",
  "bowl_food_2": "/models/parts/bowl_food/bowl_food_2.glb",
  "bowl_food_3": "/models/parts/bowl_food/bowl_food_3.glb",
  "bowl_food_4": "/models/parts/bowl_food/bowl_food_4.glb",
  "bowl_food_5": "/models/parts/bowl_food/bowl_food_5.glb",
  "bowl_food_6": "/models/parts/bowl_food/bowl_food_6.glb",
  "bowl_food_7": "/models/parts/bowl_food/bowl_food_7.glb"
} as const;
export const bowlWaterModelByIdGenerated = {
  "bowl_water_1": "/models/parts/bowl_water/bowl_water_1.glb",
  "bowl_water_2": "/models/parts/bowl_water/bowl_water_2.glb"
} as const;
