// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const houseSlotsGenerated = {
  "budka_1__base": {
    "sign": "sign_slot",
    "frameLeft": "frame_left_slot",
    "frameRight": "frame_right_slot",
    "mat": "mat_slot",
    "bowlFood": "bowl_food_slot",
    "bowlWater": "bowl_water_slot"
  }
} as const;
