CREATE TABLE "LoadingTip" (
  "id" TEXT NOT NULL,
  "text" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "LoadingTip_pkey" PRIMARY KEY ("id")
);
