// This file is auto-generated by scripts/generate-models.mjs. Do not edit manually.

export const generatedGifts = [
  {
    "code": "candle_1",
    "name": "Свеча 1",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_1.glb"
  },
  {
    "code": "candle_10",
    "name": "Свеча 10",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_10.glb"
  },
  {
    "code": "candle_11",
    "name": "Свеча 11",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_11.glb"
  },
  {
    "code": "candle_12",
    "name": "Свеча 12",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_12.glb"
  },
  {
    "code": "candle_2",
    "name": "Свеча 2",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_2.glb"
  },
  {
    "code": "candle_3",
    "name": "Свеча 3",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_3.glb"
  },
  {
    "code": "candle_4",
    "name": "Свеча 4",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_4.glb"
  },
  {
    "code": "candle_5",
    "name": "Свеча 5",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_5.glb"
  },
  {
    "code": "candle_6",
    "name": "Свеча 6",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_6.glb"
  },
  {
    "code": "candle_7",
    "name": "Свеча 7",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_7.glb"
  },
  {
    "code": "candle_8",
    "name": "Свеча 8",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_8.glb"
  },
  {
    "code": "candle_9",
    "name": "Свеча 9",
    "price": 30,
    "modelUrl": "/models/gifts/candle/candle_9.glb"
  },
  {
    "code": "flower_1",
    "name": "Цветок 1",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_1.glb"
  },
  {
    "code": "flower_10",
    "name": "Цветок 10",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_10.glb"
  },
  {
    "code": "flower_11",
    "name": "Цветок 11",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_11.glb"
  },
  {
    "code": "flower_12",
    "name": "Цветок 12",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_12.glb"
  },
  {
    "code": "flower_2",
    "name": "Цветок 2",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_2.glb"
  },
  {
    "code": "flower_3",
    "name": "Цветок 3",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_3.glb"
  },
  {
    "code": "flower_4",
    "name": "Цветок 4",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_4.glb"
  },
  {
    "code": "flower_5",
    "name": "Цветок 5",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_5.glb"
  },
  {
    "code": "flower_6",
    "name": "Цветок 6",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_6.glb"
  },
  {
    "code": "flower_7",
    "name": "Цветок 7",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_7.glb"
  },
  {
    "code": "flower_8",
    "name": "Цветок 8",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_8.glb"
  },
  {
    "code": "flower_9",
    "name": "Цветок 9",
    "price": 20,
    "modelUrl": "/models/gifts/flower/flower_9.glb"
  }
] as const;
